name: Build & push Docker image to GHCR

on:
  push:
    branches: [main]       # rebuild every time you push to main
  pull_request:            # optional: build PRs but don’t push
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # ↓ NEW: make OWNER_LC = lowercase(repository_owner)
      - name: Set lower-case image owner
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/ai-rpg:latest
            ghcr.io/${{ env.OWNER_LC }}/ai-rpg:${{ github.sha }}
          #platforms: linux/amd64,linux/arm64
