name: Build & push Docker image to GHCR

on:
  push:
    branches: [main]       # rebuild every time you push to main
  pull_request:            # optional: build PRs but don’t push
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # allow the workflow-provided GITHUB_TOKEN to write to the registry
    permissions:
      contents: read
      packages: write

    steps:
      # 1 — check out your code
      - uses: actions/checkout@v4

      # 2 — (optional) enable multi-arch builders
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # 3 — log in to ghcr.io with the ephemeral GITHUB_TOKEN
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}   # no PAT needed

      # 4 — build *and push* the image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ai-rpg:latest
            ghcr.io/${{ github.repository_owner }}/ai-rpg:${{ github.sha }}
          platforms: linux/amd64,linux/arm64   # comment out if you only need amd64
